[package]
name = "who-is-a-millionaire"
version = "0.1.0"
edition="2021"

[dependencies]
postgres = "0.19.2"
sqlx-cli = "0.5.11"
uuid = "0.8.2"
tokio-postgres = {version="0.7.5", features=["with-uuid-0_8"]}